---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# sta3262

<!-- badges: start -->
<!-- badges: end -->

Assignments for STA 326 2.0 Programming and Data Analysis

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("thiyangt/sta3262")
```

## Assignment 2: Help

This is a basic example which shows you how to solve a common problem:

### Assignment 2: Data

```{r example1, comment=NA}
library(sta3262)
## basic example code
mydata <- get_assignment_data("AS2018000") # Note: enclose index number in ""
head(mydata)
```

### Assignment 2: Questions

```{r example2, comment=NA}
get_assignment_questions(2018000) # Note: do no include "AS"

```



## Data Description

```{r a}
summary(mydata)
```

## Data Visualization

```r
confirmed <- mydata[mydata$type=="confirmed", ]
library(ggplot2)
qplot(data=confirmed, y=cases, x=date, geom="line") + ylab("confirmed cases")
```

## Assignment 3: Individual Project COVID-19 Data Analysis

```{r, comment=NA}
get_individual_project_country("AS2018000")
```
